### PR TITLE
FIX: layout problem on collapsing a node with many children 2

### PR DESCRIPTION
**Pull request by catosaurusrex2003**
Changes in the PR:
1. added a `removeEdgesByParent` function to remove the remnant edges of a node when we are collapsing it.
2. moved instance of `dagreGraph` and `getLayoutedElements` one level up from Node.tsx -> App.tsx so that every time our App.tsx rerenders a new fresh layout is created.
3. added `copyfiles` as dev dependency cuz it is used in a script in package.json

related:
https://github.com/asyncapi/website/issues/3334

### CODE REVIEW

**Review by AceTheCreator — CHANGES_REQUESTED** [review]
Can you get rid of the changes in your package.lock file?

**Comment by catosaurusrex2003** [comment]
I removed the changes to package-lock.json as requested. 

Just so I can better understand for future contributions, could you share when to include or exclude package-lock.json changes ?

**Comment by AceTheCreator** [comment]
> I removed the changes to package-lock.json as requested.
> 
> Just so I can better understand for future contributions, could you share when to include or exclude package-lock.json changes ?

That was a misunderstanding, i didn't realize you made changes to the package.json file 😄

**Comment by AceTheCreator** [comment]
@catosaurusrex2003 please kindly resolve the conflict and please return the package.lock so i can review and merge it 🙏🏽

**Comment by catosaurusrex2003** [comment]
@AceTheCreator done resolving
( i accidentally made one commit from my friends git creds 😆 )

**Review by AceTheCreator — CHANGES_REQUESTED** [review]
Looks good @catosaurusrex2003

my tiny suggestion would be when a node is collapsed, we should set the center of the view to the collapsed node. wyt?

**Comment by catosaurusrex2003** [comment]
@AceTheCreator 
nice suggestion, done :+1:

**Comment by catosaurusrex2003** [comment]
one more problem I found is

when we open or close any nodes.
the whole layout changes. which makes it hard to keep track of where other nodes are as they keep on changing position on every click.

I am willing to fix this but this will require a lot of changes.
should i do it in this pr.
or wait for this to get merged and create a new one for it.

**Comment by AceTheCreator** [comment]
> one more problem I found is
> 
> when we open or close any nodes. the whole layout changes. which makes it hard to keep track of where other nodes are as they keep on changing position on every click.
> 
> I am willing to fix this but this will require a lot of changes. should i do it in this pr. or wait for this to get merged and create a new one for it.

Yea, feel free to open a new PR 👍🏾

**Review by AceTheCreator — APPROVED** [review]

**Pull request merged**
